# -*- coding: utf-8 -*-
"""Word Count and Frequency Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThOmxCdQKxMLq8rRmCFHsFQkjJWNeSnL

Objective : Write a small program that will accept a sentence from the user, and provide a number of words, and a list of words as the output. Assume that the words are separated by blank space.
"""

# counting words using method split

x=input().split(" ")
print("Number of the words :- ",len(x))
print(x)

# counting words using nltk

import nltk

x_1=nltk.word_tokenize(input())
print("Number of the words :- ",len(x_1))
print(x_1)

# counting the frequency of unique the words using split

x_2=input().split()
x_3=x[:]
x_3.extend(x_2)

unique=list(set(x_3))
for word in unique:
    print("",word,"=",x_3.count(word))

# counting the frequency of unique the words using nltk

x_4=nltk.word_tokenize(input())
x_5=x_1[:]
x_5.extend(x_4)

unique=list(set(x_5))
for word in unique:
    print("",word,"=",x_5.count(word))

